---
- name: Update SLES server, manage services, and reboot if needed
  hosts: all
  become: true
  become_user: root

  vars:
    services_to_manage: []
    script_base_dir: "/root/scripts"

  pre_tasks:
    - name: Print a message about the playbook starting
      debug:
        msg: "Starting system update and reboot process if required..."

    - name: Check connectivity
      ping:
      register: ping_result

    - name: Fail if not reachable
      fail:
        msg: "Host {{ inventory_hostname }} is not reachable"
      when: ping_result.failed

  tasks:
    - name: Check for patches
      command: zypper list-patches | grep -v "^#" | grep -i "reboot"
      register: patches_check
      changed_when: patches_check.stdout | trim != ""
      ignore_errors: true

    - name: Set fact if patches are needed
      set_fact:
        patches_exist: "{{ patches_check.changed }}"

    - name: Display patch status
      debug:
        msg: "Patches requiring reboot: {{ patches_exist }}"

    - name: Stop services before patching
      shell: "{{ script_base_dir }}/stopVAR.sh"
      loop: "{{ services_to_manage }}"
      register: stopped_services
      ignore_errors: true
      when: patches_exist

    - name: Ensure zypper is available
      package:
        name: zypper
        state: present
      when: patches_exist

    - name: Ensure zypper cache is up to date
      command: zypper refresh
      register: refresh_result
      changed_when: refresh_result.rc == 0
      when: patches_exist

    - name: Perform a full system upgrade
      zypper:
        name: '*'
        state: latest
        update_cache: yes
      register: upgrade_result
      when: patches_exist

    - name: Check if a reboot is required (more robust check)
      shell: |
        needs_reboot=$(needs-restarting -r || echo "")
        if [[ ! -z "$needs_reboot" ]]; then
          echo "Reboot required"
        fi
      register: reboot_check
      changed_when: reboot_check.stdout | trim == "Reboot required"
      ignore_errors: true
      when: patches_exist

    - name: Set reboot fact if required
      set_fact:
        reboot_required: "{{ reboot_check.changed }}"
      when: patches_exist

    - name: Display reboot status
      debug:
        msg: "Reboot required: {{ reboot_required }}"
      when: patches_exist

    - name: Reboot the server if required
      reboot:
        msg: "Rebooting due to system updates"
      when: reboot_required and patches_exist
      register: reboot_result

  post_tasks:
    - name: Start services after reboot (or if no reboot was needed)
      shell: "{{ script_base_dir }}/startVAR.sh"
      loop: "{{ services_to_manage }}"
      when: not reboot_required or (reboot_required and reboot_result.changed)

    - name: Print a message about the playbook ending
      debug:
        msg: "System update process complete."
